module.exports = {
  AL: { fips: '01', name: 'Alabama' },
  AK: { fips: '02', name: 'Alaska' },
  AS: { fips: '60', name: 'American Samoa' },
  AZ: { fips: '04', name: 'Arizona' },
  AR: { fips: '05', name: 'Arkansas' },
  CA: { fips: '06', name: 'California' },
  CO: { fips: '08', name: 'Colorado' },
  CT: { fips: '09', name: 'Connecticut' },
  DE: { fips: '10', name: 'Delaware' },
  DC: { fips: '11', name: 'District of Columbia' },
  FM: { fips: '64', name: 'Federated States of Micronesia' },
  FL: { fips: '12', name: 'Florida' },
  GA: { fips: '13', name: 'Georgia' },
  GU: { fips: '66', name: 'Guam' },
  HI: { fips: '15', name: 'Hawaii' },
  ID: { fips: '16', name: 'Idaho' },
  IL: { fips: '17', name: 'Illinois' },
  IN: { fips: '18', name: 'Indiana' },
  IA: { fips: '19', name: 'Iowa' },
  KS: { fips: '20', name: 'Kansas' },
  KY: { fips: '21', name: 'Kentucky' },
  LA: { fips: '22', name: 'Louisiana' },
  ME: { fips: '23', name: 'Maine' },
  MH: { fips: '68', name: 'Marshall Islands' },
  MD: { fips: '24', name: 'Maryland' },
  MA: { fips: '25', name: 'Massachusetts' },
  MI: { fips: '26', name: 'Michigan' },
  MN: { fips: '27', name: 'Minnesota' },
  MS: { fips: '28', name: 'Mississippi' },
  MO: { fips: '29', name: 'Missouri' },
  MT: { fips: '30', name: 'Montana' },
  NE: { fips: '31', name: 'Nebraska' },
  NV: { fips: '32', name: 'Nevada' },
  NH: { fips: '33', name: 'New Hampshire' },
  NJ: { fips: '34', name: 'New Jersey' },
  NM: { fips: '35', name: 'New Mexico' },
  NY: { fips: '36', name: 'New York' },
  NC: { fips: '37', name: 'North Carolina' },
  ND: { fips: '38', name: 'North Dakota' },
  MP: { fips: '69', name: 'Northern Mariana Islands' },
  OH: { fips: '39', name: 'Ohio' },
  OK: { fips: '40', name: 'Oklahoma' },
  OR: { fips: '41', name: 'Oregon' },
  PW: { fips: '70', name: 'Palau' },
  PA: { fips: '42', name: 'Pennsylvania' },
  PR: { fips: '72', name: 'Puerto Rico' },
  RI: { fips: '44', name: 'Rhode Island' },
  SC: { fips: '45', name: 'South Carolina' },
  SD: { fips: '46', name: 'South Dakota' },
  TN: { fips: '47', name: 'Tennessee' },
  TX: { fips: '48', name: 'Texas' },
  UT: { fips: '49', name: 'Utah' },
  VT: { fips: '50', name: 'Vermont' },
  USVI: { fips: '78', name: 'US Virgin Islands' },
  VI: { fips: '78', name: 'US Virgin Islands' },
  VA: { fips: '51', name: 'Virginia' },
  WA: { fips: '53', name: 'Washington' },
  WV: { fips: '54', name: 'West Virginia' },
  WI: { fips: '55', name: 'Wisconsin' },
  WY: { fips: '56', name: 'Wyoming' },
}
