const stateParameter = {
  name: 'state',
  in: 'path',
  required: true,
  style: 'simple',
  explode: false,
  schema: {
    type: 'string',
    example: 'ca',
  },
  description:
    'Use the two-letter state code to select the current value for a single state.',
}

module.exports = {
  schema: 'States',
  path: 'states/daily.{format}',
  tags: ['States Current and Historical Data'],
  description: 'States historical data.',
  endpoint: 'https://covidtracking.com/api/v1/states/daily.json',
  subDefinitions: [
    {
      key: 'statesCurrent',
      schema: 'States',
      path: 'states/current.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State current values.',
    },
    {
      key: 'statesIndividualCurrent',
      schema: 'States',
      path: 'states/{state}/current.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State current values.',
      parameters: [stateParameter],
    },
    {
      key: 'statesIndividualDaily',
      schema: 'States',
      path: 'states/{state}/daily.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State daily values.',
      parameters: [stateParameter],
    },
    {
      key: 'statesIndividualByDate',
      schema: 'States',
      path: 'states/{state}/{date}.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State date values',
      parameters: [
        stateParameter,
        {
          name: 'date',
          in: 'path',
          required: true,
          style: 'simple',
          explode: false,
          schema: {
            type: 'string',
            example: '20200501',
          },
          description:
            'Use the ISO-formatted date, without hyphens, to select just the data for a specific date.',
        },
      ],
    },
  ],
  fieldDefinitions: [
    {
      source: 'date',
      target: 'date',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: false,
      example: 20200501,
    },
    {
      source: 'state',
      target: 'state',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: false,
      example: '',
    },
    {
      source: 'fips',
      target: 'fips',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: false,
      example: '',
    },
    {
      source: 'positive',
      target: 'positive',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },

    {
      source: 'positiveIncrease',
      target: 'positiveIncrease',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'negative',
      target: 'negative',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },

    {
      source: 'negativeIncrease',
      target: 'negativeIncrease',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'pending',
      target: 'pending',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'total',
      target: 'total',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'totalTestResults',
      target: 'totalTestResults',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'totalTestResultsIncrease',
      target: 'totalTestResultsIncrease',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'posNeg',
      target: 'posNeg',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalizedCurrently',
      target: 'hospitalizedCurrently',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalizedCumulative',
      target: 'hospitalizedCumulative',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalizedCumulative',
      target: 'hospitalizedCumulative',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'inIcuCurrently',
      target: 'inIcuCurrently',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'inIcuCumulative',
      target: 'inIcuCumulative',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'onVentilatorCurrently',
      target: 'onVentilatorCurrently',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'onVentilatorCumulative',
      target: 'onVentilatorCumulative',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'recovered',
      target: 'recovered',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'dataQualityGrade',
      target: 'dataQualityGrade',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'lastUpdateEt',
      target: 'lastUpdateEt',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'recovered',
      target: 'recovered',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'death',
      target: 'death',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'death',
      target: 'death',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'deathIncrease',
      target: 'deathIncrease',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalized',
      target: 'hospitalized',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalizedIncrease',
      target: 'hospitalizedIncrease',
      type: 'number',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'total',
      target: 'total',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: false,
      example: '',
    },
    {
      source: 'dateChecked',
      target: 'dateChecked',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: false,
      example: '',
    },
    {
      source: 'hash',
      target: 'hash',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: false,
      example: '',
    },
  ],
}
