const { DateTime } = require('luxon')
const objectHash = require('object-hash')
const stateNames = require('../state-names')

const stateParameter = {
  name: 'state',
  in: 'path',
  required: true,
  style: 'simple',
  explode: false,
  schema: {
    type: 'string',
    example: 'ca',
  },
  description:
    'Use the two-letter state code to select the current value for a single state.',
}

module.exports = {
  schema: 'States',
  path: 'states/daily.{format}',
  tags: ['States Current and Historical Data'],
  description: 'States historical data.',
  endpoint:
    'http://covid-publishing-api-stage.us-east-1.elasticbeanstalk.com/api/v1/public/states/daily',
  subDefinitions: [
    {
      key: 'statesCurrent',
      schema: 'States',
      path: 'states/current.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State current values.',
    },
    {
      key: 'statesIndividualCurrent',
      schema: 'States',
      path: 'states/{state}/current.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State current values.',
      parameters: [stateParameter],
    },
    {
      key: 'statesIndividualDaily',
      schema: 'States',
      path: 'states/{state}/daily.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State daily values.',
      parameters: [stateParameter],
    },
    {
      key: 'statesIndividualByDate',
      schema: 'States',
      path: 'states/{state}/{date}.{format}',
      tags: ['States Current and Historical Data'],
      description: 'State date values',
      parameters: [
        stateParameter,
        {
          name: 'date',
          in: 'path',
          required: true,
          style: 'simple',
          explode: false,
          schema: {
            type: 'string',
            example: '20200501',
          },
          description:
            'Use the ISO-formatted date, without hyphens, to select just the data for a specific date.',
        },
      ],
    },
  ],
  fieldDefinitions: [
    {
      source: 'date',
      target: 'date',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: false,
      example: 20200501,
      format: (date) =>
        parseInt(DateTime.fromRFC2822(date).toFormat('yyyyLLdd'), 10),
    },
    {
      source: 'state',
      target: 'state',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: false,
      example: '',
    },
    {
      source: 'fips',
      target: 'fips',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) =>
        typeof stateNames[item.state] !== 'undefined'
          ? stateNames[item.state].fips
          : 0,
    },
    {
      source: 'positive',
      target: 'positive',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },

    {
      source: 'positiveIncrease',
      target: 'positiveIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => 0,
    },
    {
      source: 'negative',
      target: 'negative',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },

    {
      source: 'negativeIncrease',
      target: 'negativeIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => 0,
    },
    {
      source: 'pending',
      target: 'pending',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'total',
      target: 'total',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) =>
        (item.positive || 0) + (item.negative || 0) + (item.pending || 0),
    },
    {
      source: 'totalTestResults',
      target: 'totalTestResults',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => item.positive + item.negative,
    },
    {
      source: 'totalTestResultsIncrease',
      target: 'totalTestResultsIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => 0,
    },
    {
      source: 'posNeg',
      target: 'posNeg',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => item.positive + item.negative,
    },
    {
      source: 'hospitalizedCurrently',
      target: 'hospitalizedCurrently',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalizedCumulative',
      target: 'hospitalizedCumulative',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'inIcuCurrently',
      target: 'inIcuCurrently',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'inIcuCumulative',
      target: 'inIcuCumulative',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'onVentilatorCurrently',
      target: 'onVentilatorCurrently',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'onVentilatorCumulative',
      target: 'onVentilatorCumulative',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'recovered',
      target: 'recovered',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'dataQualityGrade',
      target: 'dataQualityGrade',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'lastUpdateEt',
      target: 'lastUpdateEt',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'lastUpdateEt',
      target: 'dateModified',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
      format: (date) =>
        date
          ? DateTime.fromRFC2822(date)
              .setZone('UTC')
              .toFormat(`yyyy-LL-dd'T'TT'Z'`)
          : null,
    },
    {
      source: 'lastUpdateEt',
      target: 'checkTimeEt',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
      format: (date) =>
        date
          ? DateTime.fromRFC2822(date)
              .setZone('America/New_York')
              .toFormat(`LL/dd HH:mm`)
          : null,
    },
    {
      source: 'death',
      target: 'death',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'deathIncrease',
      target: 'deathIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => 0,
    },
    {
      source: 'hospitalizedCumulative',
      target: 'hospitalized',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
    },
    {
      source: 'hospitalizedIncrease',
      target: 'hospitalizedIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => 0,
    },
    {
      source: 'lastUpdateEt',
      target: 'dateChecked',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
      format: (date) =>
        date ? DateTime.fromRFC2822(date).toFormat(`yyyy-LL-dd'T'TT'Z'`) : null,
    },
    {
      source: 'hash',
      target: 'hash',
      type: 'string',
      graphQlType: 'String',
      description: '',
      nullable: true,
      example: '',
      sourceFunction: (item) => objectHash(item),
    },
    {
      source: 'commercialScore',
      target: 'commercialScore',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: '',
      sourceFunction: () => 0,
    },
    {
      source: 'negativeRegularScore',
      target: 'negativeRegularScore',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: '',
      sourceFunction: () => 0,
    },
    {
      source: 'negativeScore',
      target: 'negativeScore',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: '',
      sourceFunction: () => 0,
    },
    {
      source: 'positiveScore',
      target: 'positiveScore',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: '',
      sourceFunction: () => 0,
    },
    {
      source: 'score',
      target: 'score',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: '',
      sourceFunction: () => 0,
    },
    {
      source: 'grade',
      target: 'grade',
      type: 'string',
      graphQlType: 'String',
      description: 'Deprecated',
      nullable: true,
      example: '',
      sourceFunction: () => '',
    },
  ],
}
