const { DateTime } = require('luxon')
const objectHash = require('object-hash')

const xPublicSourceUrl =
  'https://docs.google.com/spreadsheets/u/2/d/e/2PACX-1vRwAqp96T9sYYq2-i7Tj0pvTf6XVHjDSMIKBdZHXiCGGdNC0ypEU9NbngS8mxea55JuCFuua1MUeOj5/pubhtml#'

module.exports = {
  schema: 'Us',
  formats: ['json', 'csv'],
  path: 'us/daily.{format}',
  tags: ['US Current and Historical Data'],
  summary: 'Historic US values',
  description: 'All COVID data for the US.',
  xPublicSourceUrl,
  endpoint: 'http://internalapi.covidtracking.com/api/v1/public/us/daily',
  subDefinitions: [
    {
      key: 'usCurrent',
      schema: 'Us',
      path: 'us/current.{format}',
      tags: ['US Current and Historical Data'],
      summary: 'Current US values',
      description:
        'The most recent COVID data for the US. The most recent data may not be from today.',
      xPublicSourceUrl,
    },
    {
      key: 'usDates',
      schema: 'Us',
      path: 'us/{date}.{format}',
      tags: ['US Current and Historical Data'],
      summary: 'US historic values for a date',
      description: 'All COVID data for the US on a specific date.',
      xPublicSourceUrl,
      parameters: [
        {
          name: 'date',
          in: 'path',
          required: true,
          style: 'simple',
          explode: false,
          schema: {
            type: 'string',
            example: '20200501',
          },
          description:
            'Use the ISO-formatted date, without hyphens, to select just the data for a specific date.',
        },
      ],
    },
  ],
  fieldDefinitions: [
    {
      source: 'date',
      target: 'date',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Date for which the daily totals were collected.',
      nullable: false,
      example: 20200501,
    },
    {
      source: 'positive',
      target: 'positive',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have tested positive for COVID-19 so far.',
      nullable: true,
      example: 50,
    },

    {
      source: 'negative',
      target: 'negative',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have tested negative for COVID-19 so far.',
      nullable: true,
      example: 50,
    },
    {
      source: 'pending',
      target: 'pending',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Number of tests whose results have yet to be determined.',
      nullable: true,
      example: 50,
    },
    {
      source: 'hospitalizedCurrently',
      target: 'hospitalizedCurrently',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Number of people in hospital for COVID-19 on this day.',
      nullable: true,
      example: 50,
    },
    {
      source: 'hospitalizedCumulative',
      target: 'hospitalizedCumulative',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have gone to the hospital for COVID-19 so far, including those who have since recovered or died.',
      nullable: true,
      example: 50,
    },
    {
      source: 'inIcuCurrently',
      target: 'inIcuCurrently',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people in the ICU for COVID-19 on this day.',
      nullable: true,
      example: 50,
    },
    {
      source: 'inIcuCumulative',
      target: 'inIcuCumulative',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have gone to the ICU for COVID-19 so far, including those who have since recovered or died.',
      nullable: true,
      example: 50,
    },
    {
      source: 'onVentilatorCurrently',
      target: 'onVentilatorCurrently',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Number of people using a ventilator for COVID-19 on this day.',
      nullable: true,
      example: 50,
    },
    {
      source: 'onVentilatorCumulative',
      target: 'onVentilatorCumulative',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have used a ventilator for COVID-19 so far, including those who have since recovered or died.',
      nullable: true,
      example: 50,
    },

    {
      source: 'recovered',
      target: 'recovered',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have recovered from COVID-19 so far.',
      nullable: true,
      example: 50,
    },
    {
      source: 'dateChecked',
      target: 'dateChecked',
      type: 'string',
      graphQlType: 'String',
      description: 'DateTime this data was entered into our database.',
      nullable: true,
      example: 50,
      format: (date) =>
        DateTime.fromISO(date).setZone('UTC').toFormat(`yyyy-LL-dd'T'TT'Z'`),
    },
    {
      source: 'death',
      target: 'death',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of people who have died as a result of COVID-19 so far.',
      nullable: true,
      example: 50,
    },
    {
      source: 'antibodyNegative',
      target: 'antibodyNegative',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of negative antibody tests.',
      nullable: true,
      example: 50,
    },
    {
      source: 'antibodyPositive',
      target: 'antibodyPositive',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of positive antibody tests.',
      nullable: true,
      example: 50,
    },
    {
      source: 'antibodyTotal',
      target: 'antibodyTotal',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of antibody tests.',
      nullable: true,
      example: 50,
    },
    {
      source: 'deathConfirmed',
      target: 'deathConfirmed',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of deaths confirmed to be caused by COVID-19.',
      nullable: true,
      example: 50,
    },
    {
      source: 'deathProbable',
      target: 'deathProbable',
      type: 'integer',
      graphQlType: 'Int',
      description:
        'Total number of deaths where it is probable that theyw were caused by COVID-19.',
      nullable: true,
      example: 50,
    },
    {
      source: 'pcrNegativeTests',
      target: 'pcrNegativeTests',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of negative PCR tests.',
      nullable: true,
      example: 50,
    },
    {
      source: 'pcrPositiveCases',
      target: 'pcrPositiveCases',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of positive PCR cases.',
      nullable: true,
      example: 50,
    },
    {
      source: 'pcrPositiveTests',
      target: 'pcrPositiveTests',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total number of positive PCR tests.',
      nullable: true,
      example: 50,
    },
    {
      source: 'pcrTotalTests',
      target: 'pcrTotalTests',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Total PCR tests.',
      nullable: true,
      example: 50,
    },
    {
      source: 'positiveConfirmed',
      target: 'positiveConfirmed',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: 50,
    },
    {
      source: 'totalTestsPeople',
      target: 'totalTestsPeople',
      type: 'integer',
      graphQlType: 'Int',
      description: '',
      nullable: true,
      example: 50,
    },
    {
      source: 'hospitalizedCumulative',
      target: 'hospitalized',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
    },
    {
      source: 'total',
      target: 'total',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => item.positive + item.negative + item.pending,
    },
    {
      source: 'totalTestResults',
      target: 'totalTestResults',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => item.positive + item.negative,
    },
    {
      source: 'posNeg',
      target: 'posNeg',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => item.positive + item.negative,
    },
    {
      source: 'deathIncrease',
      target: 'deathIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => 0,
    },
    {
      source: 'hospitalizedIncrease',
      target: 'hospitalizedIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => 0,
    },
    {
      source: 'negativeIncrease',
      target: 'negativeIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => 0,
    },
    {
      source: 'positiveIncrease',
      target: 'positiveIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => 0,
    },
    {
      source: 'totalTestResultsIncrease',
      target: 'totalTestResultsIncrease',
      type: 'integer',
      graphQlType: 'Int',
      description: 'Deprecated',
      nullable: true,
      example: 50,
      sourceFunction: (item) => 0,
    },
    {
      source: 'date',
      target: 'lastModified',
      type: 'string',
      graphQlType: 'String',
      description: 'Deprecated',
      nullable: false,
      example: '2020-05-27T12:18:23.392Z',
      format: (date) =>
        DateTime.fromISO(date).setZone('UTC').toFormat(`yyyy-LL-dd'T'TT'Z'`),
    },
    {
      source: 'hash',
      target: 'hash',
      type: 'string',
      graphQlType: 'String',
      description: 'A hash for this record',
      nullable: false,
      example: 50,
      sourceFunction: (item) => objectHash(item),
    },
  ],
}
