name: API build
on:
  repository_dispatch:
    types: [api-build]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          ref: master
          repository: 'COVID19Tracking/covid-public-api'
          token: ${{ secrets.API_DEPLOY_TOKEN }}
          ref: api-2
          path: ./_api

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # yarn cache files are stored in `~/.yarn` on Linux/macOS
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn install

      - name: Build API files
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          INTERNAL_API_HOST: internalapi.covidtracking.com
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
        run: |
          yarn run build
          yarn run test:post-build

      - name: Send webhook
        env:
          SITE_BUILD_WEBHOOK: ${{ secrets.SITE_BUILD_WEBHOOK }}
        run: yarn run webhook

      - name: Commit API files
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update API data
          repository: ./_api
          file_pattern: ./**
          commit_author: COVID Tracking Project API Builder <accounts@covidtracking.com>

      - name: Prepare artifacts
        run: |
          rm -rf ./_api/.git
          tar -czvf api-files.tar.gz ./_api

      - name: Upload API artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-files
          path: ./api-files.tar.gz
