name: API build
on:
  push:
    branches:
      - master

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          ref: master
          repository: 'COVID19Tracking/covid-public-api'
          token: ${{ secrets.API_DEPLOY_TOKEN }}
          path: ./_api

      - name: Build API files
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          npm install
          node index.js

      - name: Commit API files
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          ref: master
          commit_message: Update API data
          repository: ./_api
          file_pattern: ./**
          commit_author: COVID Tracking Project API Builder <accounts@covidtracking.com>
